stderr of test 'dvf` in directory 'extras/dvf` itself:


# 17:17:56 >  
# 17:17:56 >  "/usr/bin/python" "dvf.py" "dvf"
# 17:17:56 >  

# builtin opt 	gdk_dbname = demo
# builtin opt 	gdk_dbfarm = /export/scratch2/kargin/Monet/dft_miniseed/PREFIX/DFT/var/monetdb5/dbfarm
# builtin opt 	gdk_debug = 0
# builtin opt 	gdk_vmtrim = yes
# builtin opt 	monet_prompt = >
# builtin opt 	monet_daemon = no
# builtin opt 	mapi_port = 50000
# builtin opt 	mapi_open = false
# builtin opt 	mapi_autosense = false
# builtin opt 	sql_optimizer = default_pipe
# builtin opt 	sql_debug = 0
# cmdline opt 	gdk_nr_threads = 0
# cmdline opt 	gdk_dbfarm = /export/scratch2/kargin/Monet/dft_miniseed/PREFIX/DFT/var/MonetDB
# cmdline opt 	mapi_open = true
# cmdline opt 	mapi_port = 37875
# cmdline opt 	monet_prompt = 
# cmdline opt 	mal_listing = 2
# cmdline opt 	gdk_dbname = mTests_extras_dvf
# cmdline opt 	gdk_readonly = yes

# 17:17:57 >  
# 17:17:57 >  "Done."
# 17:17:57 >  

